# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.7"

Vagrant.configure("2") do |config|

  config.trigger.before :up do |trigger|
    trigger.name = "ssh-agent started"
    trigger.info = "Confirming ssh-agent started and keys available before starting."
    trigger.run = {inline: "ssh-add -l"}
  end

  config.vm.box = "launchquickly/focal64"
  config.vm.box_version = "0.0.3"

  # Set-up SSH agent forwarding
  config.ssh.forward_agent = true
end
