# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "launchquickly/focal-desktop64"
  config.vm.box_version = "0.0.2"

  config.vm.hostname = "focal-desktop64"

  config.vm.network "public_network", ip: "192.168.0.110"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end
end
