# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.9"

Vagrant.configure("2") do |config|
  config.vm.box = "launchquickly/focal64"
  config.vm.box_version = "0.0.4"

  config.vm.hostname = "focal64"
  
  config.vm.network "public_network", ip: "192.168.0.120"

  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '../keys/id_rsa_focal64']

  config.vm.provision "file", source: "../keys/id_rsa_focal64.pub", destination: "~/.ssh/authorized_keys"

end
