# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "launchquickly/focal64"
  config.vm.box_version = "0.0.1"

  config.vm.hostname = "focal64"
  
  config.vm.network "public_network", ip: "192.168.0.120"

end
