# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "launchquickly/focal-desktop64"
   config.vm.box_version = "0.0.2"

   config.vm.hostname = "vscode"

   config.vm.network "public_network" ,ip: "192.168.0.111"

   config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--vram", "128"]
   end

   config.vm.provision "shell", inline: <<-SHELL
      snap install code --classic
   SHELL

   # Run as unpriviliged user to configure for 'vagrant' user
   config.vm.provision "shell", privileged: false, inline: <<-SHELL
     code --install-extension ms-vscode-remote.remote-ssh
   SHELL

   # Make private keys of instances that vscode will connect to available
   config.vm.provision "file", source: "../keys/id_rsa_focal64", destination: "~/.ssh/id_rsa_focal64"

   config.vm.provision "file", source: "./config", destination: "~/.ssh/config"

   config.vm.provision "shell", privileged: false, inline: <<-SHELL
     chmod 400 ~/.ssh/id_rsa_focal64

     chmod 400 ~/.ssh/config
   SHELL

end