# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "code" do |code|
    code.vm.box = "launchquickly/focal-desktop64"
    code.vm.box_version = "0.0.4"

    code.vm.hostname = "code"

    code.vm.network :private_network, ip: "192.168.205.10"

    code.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--vram", "128"]
    end

    code.vm.provision "shell", inline: <<-SHELL
      snap install code --classic
    SHELL

    # Run as unpriviliged user to configure for 'vagrant' user
    code.vm.provision "shell", privileged: false, inline: <<-SHELL
      code --install-extension ms-vscode-remote.remote-ssh
    SHELL

    # Make private keys of instances that vscode will connect to available
    code.vm.provision "file", source: "./keys/id_rsa_web", destination: "~/.ssh/id_rsa_web"

    code.vm.provision "file", source: "./config", destination: "~/.ssh/config"

    code.vm.provision "shell", privileged: false, inline: <<-SHELL
      chmod 400 ~/.ssh/id_rsa_web
      
      chmod 400 ~/.ssh/config
    SHELL
  end

  config.vm.define "web" do |web|
    web.vm.box = "launchquickly/focal64"
    web.vm.box_version = "0.0.3"

    web.vm.hostname = "web"

    web.vm.network :private_network, ip: "192.168.205.20"

    web.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', './keys/id_rsa_web']

    web.vm.provision "file", source: "./keys/id_rsa_web.pub", destination: "~/.ssh/authorized_keys"
  end

end
